export interface Card {
  type: 'truth' | 'dare' | 'penalty';
  content: string;
}

export const DEFAULT_CARDS: Card[] = [
  // ── Truth ──
  { type: 'truth', content: 'Were you genuinely happy this past year?' },
  { type: 'truth', content: 'Do you truly love yourself?' },
  { type: 'truth', content: 'If you could act in any movie, what role would you choose?' },
  { type: 'truth', content: 'Have you ever completely lost motivation in life?' },
  { type: 'truth', content: 'What disappoints you most about yourself?' },
  { type: 'truth', content: 'What is your most unforgettable moment from this past year?' },
  { type: 'truth', content: 'Do you feel like you missed out on anything important this year?' },
  { type: 'truth', content: 'What is one thing you are genuinely proud of right now?' },
  { type: 'truth', content: 'Have you ever been deeply in love with someone?' },
  { type: 'truth', content: 'What career did you dream of as a child?' },
  { type: 'truth', content: 'If you could go back in time, what one thing would you change?' },
  { type: 'truth', content: 'If you knew the world was ending tomorrow, what would you do today?' },
  { type: 'truth', content: 'What would you do first if you won the lottery?' },
  { type: 'truth', content: 'Would you want the ability to read other people\'s minds? Why or why not?' },
  { type: 'truth', content: 'Do you use people around you as role models for self-improvement?' },
  { type: 'truth', content: 'Do you often talk about your life struggles with your family?' },
  { type: 'truth', content: 'When was the last time you told someone "I love you" and meant it?' },
  { type: 'truth', content: 'What is one thing someone did that genuinely hurt you?' },
  { type: 'truth', content: 'What is the longest you have been away from home?' },
  { type: 'truth', content: 'Do you ever question whether you are living your life the right way?' },
  { type: 'truth', content: 'What is one thing you wish you could do for the people you love?' },
  { type: 'truth', content: 'Have you ever traveled completely alone? How was it?' },
  { type: 'truth', content: 'Have you ever done something embarrassing in public?' },
  { type: 'truth', content: 'What is the most childish thing you still secretly do?' },
  { type: 'truth', content: 'Have you ever been scammed while shopping online?' },
  { type: 'truth', content: 'What is the biggest regret of your life so far?' },
  { type: 'truth', content: 'Who is the single most influential person in your life?' },
  { type: 'truth', content: 'What animal do you feel most like, and why?' },
  { type: 'truth', content: 'Have you ever missed a chance at love because you were too shy to confess?' },
  { type: 'truth', content: 'What is the most annoying lie you have ever been told?' },
  { type: 'truth', content: 'What is the most ridiculous lie you have ever told?' },
  { type: 'truth', content: 'In order of importance, rank: love, career, family.' },
  { type: 'truth', content: 'What creature are you most afraid of?' },
  { type: 'truth', content: 'Tell everyone about a crazy or funny memory from high school.' },
  { type: 'truth', content: 'What is the weirdest dream you have ever had?' },
  { type: 'truth', content: 'What is the longest you have gone without showering? Be honest.' },
  { type: 'truth', content: 'What is the most embarrassing thing you did as a child?' },
  { type: 'truth', content: 'Share a childhood memory you will never forget.' },
  { type: 'truth', content: 'Have you ever had a crush on someone much older than you?' },
  { type: 'truth', content: 'How old were you when you first fell in love?' },
  { type: 'truth', content: 'Have you ever been drunk? What happened?' },
  { type: 'truth', content: 'What is the most foolish thing you did while drunk?' },
  { type: 'truth', content: 'How old were you when you had your first kiss?' },
  { type: 'truth', content: 'What job or career could you never imagine yourself doing?' },
  { type: 'truth', content: 'If stranded on a deserted island for 5 days, what 3 things would you bring?' },
  { type: 'truth', content: 'What is a secret talent no one here knows about?' },
  { type: 'truth', content: 'What is something you have never told your parents?' },
  { type: 'truth', content: 'What is your biggest fear in life?' },
  { type: 'truth', content: 'Have you ever ghosted someone? How do you feel about it now?' },
  { type: 'truth', content: 'What is one habit you are ashamed of?' },
  { type: 'truth', content: 'What is the most money you have ever wasted on something stupid?' },

  // ── Dare ──
  { type: 'dare', content: 'Call a friend, pretend it\'s their birthday, and sing Happy Birthday to them.' },
  { type: 'dare', content: 'End every sentence you say for the next 3 rounds with "...but anyway."' },
  { type: 'dare', content: 'Make up a dramatic story about two random objects in the room.' },
  { type: 'dare', content: 'Go up to someone nearby and say "I believe in unicorns" with complete seriousness.' },
  { type: 'dare', content: 'Rap 2 lines introducing the player sitting next to you.' },
  { type: 'dare', content: 'Impersonate a famous celebrity until someone guesses who it is.' },
  { type: 'dare', content: 'Post something completely random on social media and leave it up for 30 minutes.' },
  { type: 'dare', content: 'Do your best impression of the player to your left.' },
  { type: 'dare', content: 'Speak in a foreign accent for the next 2 rounds.' },
  { type: 'dare', content: 'Let the group give you a new hairstyle for 5 minutes.' },
  { type: 'dare', content: 'Sing the first 30 seconds of any song chosen by the group.' },
  { type: 'dare', content: 'Text your most recent contact "I have a confession to make…" and wait for their reply.' },
  { type: 'dare', content: 'Describe the person to your right using only food.' },
  { type: 'dare', content: 'Do 15 push-ups right now.' },
  { type: 'dare', content: 'Let someone else post anything they want on your social media — within reason.' },
  { type: 'dare', content: 'Recite the alphabet backwards as fast as you can.' },
];
